# docker-compose.yml
version: '3.8'

services:
  api-user-bridge:
    container_name: api-user-bridge
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres-user-bridge  # This needs to match the service name below
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=user_bridge
    depends_on:
      postgres-user-bridge:
        condition: service_healthy
    
  postgres-user-bridge:
    container_name: postgres-user-bridge
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_bridge
    volumes:
      - postgres_data_userbridge:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_userbridge: